### ISSUE TITLE
Something wrong on editing this extension

### ISSUE THREAD

**Issue by navarma** [rvspt/GoogleMapsAPIv3Toolkit-QS#1]
Hi,
I've downloaded this extension, but for some reason when I edit the code, nothing happen. For example, on updateMapPosition function I've change default position but is still focusing on Portugal. I know that Qlikview is taking this code because when I delete primary file the map doesn't appear.
What could be happening?

**Comment by rvspt** [comment]
Hello, 

This is the Qlik Sense version of the extension. Not QlikView. 
In this version the default is pointing to Lund in Sweden where are the Qlik Offices. That value can be found indeed in the updateMapPosition function on line 216 and it is (55.716258,13.221009).

From your comment, I think you are referring to QlikView version of the extension that is in another repository:
https://github.com/rvspt/GoogleMapsAPIv3Toolkit-QV

You can update the map's default value on line 132, changing 

```
map.setCenter(new google.maps.LatLng(41.348205,-8.19274));
```

accordingly.

**Comment by rvspt** [comment]
Closing as this is related to another extension
