### ISSUE TITLE
Extension Error

### ISSUE THREAD

**Issue by wmj1113** [rvspt/GoogleMapsAPIv3Toolkit-QS#2]
Hi Sir,

The extension with error "This page didn't load Google Maps correctly. See the JavaScript console for technical details". Any solution to solve this problem?

Thanks.

Best Regards.

**Comment by eso-mikl** [comment]
Hello,

I think it is all about API key and MissingKeyMapError. To solve this error, somebody must add API key form item. 

https://churchthemes.com/2016/07/15/page-didnt-load-google-maps-correctly/#MissingKeyMapError

Have a nice day.

**Comment by rvspt** [comment]
Check v1.2.1. I added a possibility to specify your Google Maps API Key. This is now a request even for the standard plan. Tutorial and help within the extension should be self explanatory to help you get back on track.
