### ISSUE TITLE
Not uploading with 3.1? 

### ISSUE THREAD

**Issue by kframnes1** [rvspt/GoogleMapsAPIv3Toolkit-QS#3]
Hi. Will this be updated and tested so it works with Qlik Sense 3.1? Not desktop :) Thank you

**Comment by rvspt** [comment]
Hello, it works with 3.1.

Might be related to the need of a Google API Key. My example qvf file has no key associated so I don't risk to have a surprise bill at the end of the month :) 
But if you create one API key, it will work. Using the latest version of the extension you will get a walkthrough/help message when you drag it to your sheet to help you get one API key.
