### ISSUE TITLE
Maps not loading

### ISSUE THREAD

**Issue by ckaros** [rvspt/GoogleMapsAPIv3Toolkit-QS#4]
I am looking to try out this extension with QLIK Sense 3.1 SR3 but am having no luck. 

Firstly, I cannot figure out how to input an api key. The Readme says to look in the Example app, but I was unable to find any specific information on how to input the key. Googling the question points me towards the Map Basic Configuration Properties drop-down, but I see no option for an API key there. Can anyone help out with this?

**Comment by rvspt** [comment]
Some properties could be omitted due to an incorrect extension-properties.js definition. Should be corrected with current release.
