### ISSUE TITLE
Extension not deallocate memory from browser

### ISSUE THREAD

**Issue by eduardodimperio** [rvspt/GoogleMapsAPIv3Toolkit-QS#5]
Hi, 

Im using this extension and not a problem at all to implement, but as long i check and uncheck some States to pins positions, the consume of memory raise everytime until crash. Tha happen only on my browser, the server its ok.
Follow the images.

![maps_1check](https://user-images.githubusercontent.com/5177743/26987862-810e5558-4d23-11e7-8569-f71ed22bafce.JPG)
![maps_2check](https://user-images.githubusercontent.com/5177743/26987863-810ec696-4d23-11e7-8126-f71f9c58d6bc.JPG)
![maps_3check](https://user-images.githubusercontent.com/5177743/26987861-810e626e-4d23-11e7-9e84-88c60c81cc67.JPG)
![maps_4check](https://user-images.githubusercontent.com/5177743/26987859-810b75cc-4d23-11e7-96c6-6e3d75912023.JPG)
![maps_nocheck](https://user-images.githubusercontent.com/5177743/26987860-810cd142-4d23-11e7-8b66-d1d2c1ed8112.JPG)

**Comment by rvspt** [comment]
Rendering depends on consuming user browser's performance, which is heavily related to hardware power available and the web browser engine itself (not only of course, but these are key points). Reduce the number of points to display with drill/aggregation techniques and you should be ok.
