### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by mehdawi77** [rvspt/GoogleMapsAPIv3Toolkit-QS#9]
Dear Sir,

Where should place the API key inside the extension properties file?

Thanks.

**Comment by rvspt** [comment]
Place it in the extension properties pane within the app. Ensure you are using latest version as there was an issue that was not allowing the properties pane to be completely rendered.

Here is a screenshot:
![apikeygoogle](https://user-images.githubusercontent.com/6049853/44852090-433e7180-ac5a-11e8-8404-5205e534df02.PNG)

**Comment by mehdawi77** [comment]
Thanks for your support; it is working like charm.
